version: '3.8'
services:
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=ecommerce_db
      - DB_USER=ecommerce_user
      - DB_PASS=ecommerce_password
    networks:
      - ecommerce_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: ecommerce_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - ecommerce_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - ecommerce_network

networks:
  ecommerce_network:

volumes:
  mysql_data: