apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: php-apache
        image: ${{ secrets.DOCKER_USERNAME }}/my-ecommerce-app:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "db-service"
        - name: DB_NAME
          value: "ecommerce_db"
        - name: DB_USER
          value: "ecommerce_user"
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
