name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t my-ecommerce-app:latest ./web
        docker tag my-ecommerce-app:latest ${{ secrets.DOCKER_USERNAME }}/my-ecommerce-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-ecommerce-app:latest

  deploy:
    name: Deploy to k3s Cluster
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up kubectl for k3s
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.K3S_KUBECONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Deploy to k3s
      run: |
        kubectl apply -f .\k3s\deployment.yaml
        kubectl apply -f .\k3s\service.yaml
