name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t my-ecommerce-app:latest ./web
        docker tag my-ecommerce-app:latest ${{ secrets.DOCKER_USERNAME }}/my-ecommerce-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-ecommerce-app:latest

  deploy:
    name: Deploy to K3s via Bastion Host
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Connect to Bastion Host and Deploy to K3s
      run: |
        # Open an SSH connection via the bastion host and execute kubectl commands
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }} \
        "kubectl apply -f ./k3s/deployment.yaml && kubectl apply -f ./k3s/service.yaml"
