name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted # k3s is lokaal bereikbaar via je runner

    steps:
    # Stap 1: Haal de code op uit je repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Stap 2: Set up PHP zonder sudo
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        ini-file: production
        tools: composer

    # Stap 3: Installeer Composer dependencies
    - name: Install Dependencies
      run: composer install --no-progress --no-suggest --prefer-dist

    # Stap 4: Voer Unit Tests uit
    - name: Run Unit Tests
      run: vendor/bin/phpunit --testdox tests/

    # Stap 5: Build en Push Docker Image naar Docker Hub
    - name: Build en Push Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker build -t $DOCKER_USERNAME/ecommerce-web:latest ./web
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push $DOCKER_USERNAME/ecommerce-web:latest

    # Stap 6: Configure Kubernetes Context
    - name: Configure Kubernetes Context
      env:
        KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}
      run: |
        mkdir -p $HOME/.kube
        echo "$KUBECONFIG_CONTENT" | base64 -d > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    # Stap 7: Cleanup bestaande resources
    - name: Cleanup Existing Resources
      run: |
        kubectl delete deployment ecommerce-web --ignore-not-found
        kubectl delete deployment ecommerce-db --ignore-not-found
        kubectl delete deployment phpmyadmin --ignore-not-found
        kubectl delete service ecommerce-web-service --ignore-not-found
        kubectl delete service ecommerce-db --ignore-not-found
        kubectl delete service phpmyadmin-service --ignore-not-found

    # Stap 8: Deploy naar k3s cluster
    - name: Deploy to k3s Cluster
      run: |
        kubectl apply -f k3s/secrets.yaml
        kubectl apply -f k3s/web-deployment.yaml
        kubectl apply -f k3s/db-deployment.yaml
        kubectl apply -f k3s/phpmyadmin-deployment.yaml

    # Stap 9: Haal het Node-IP op voor Integratietests
    - name: Get External IP
      id: get-ip
      run: |
        NODE_IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')
        echo "WEB_SERVER_URL=http://$NODE_IP:30080" >> $GITHUB_ENV

    # Stap 10: Run Integratietests
    - name: Run Integration Tests
      env:
        WEB_SERVER_URL: ${{ env.WEB_SERVER_URL }}
      run: vendor/bin/phpunit --testdox tests/IntegrationTest.php

    # Stap 11: Verifieer de status van pods en services
    - name: Verify Deployment
      run: |
        kubectl get pods
        kubectl get services
